# Generated by Django 4.2.11 on 2024-03-17 10:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='additional_info',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
