# Generated by Django 4.2.11 on 2024-03-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_reservation_email_reservation_is_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('s', 'Single'), ('d', 'Double'), ('st', 'Suit')], default='s', max_length=10),
        ),
    ]
