# Generated by Django 4.2.11 on 2024-04-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_hotel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='modiefied_at',
            field=models.DateField(auto_now=True),
        ),
    ]
